### ISSUE TITLE
Flexibilize usage

### ISSUE THREAD

**Issue by shawninder** [vigour-io/vigour-img#2]
Currently only runs as a web service, should also be possible to run one-time operations from the command line or from within another javascript script.

Also offer a general-use server for image manipulation capable of uploading the source images (makes local use possible without installing ImageMagick)

Also need to invent the verb "flexibilize"

**Comment by jimdebeer** [comment]
As an extra flexible feature (for platforms where you can't install imagemagixx with a simple npm i) I would like to suggest adding a remote option. 

**basically what it does**
Installs the img server locally , but instead of using a local imgmagixx it forwards all the requests (and files) to a server and receives images over the network when done

_protip: support batched requests and responses_

**Comment by shawninder** [comment]
I don't think we need that, all we need is automated launching, and then you make your requests directly to the remote, no need for a local running process

**Comment by shawninder** [comment]
Allow POSTing image as an alternative to providing a URL

**Comment by jimdebeer** [comment]
the idea for the remote is to support cli deps for for examples native builds (even when you cant install imgmagixx)

**Comment by shawninder** [comment]
Supporting POSTed images will help with manipulating images that reside on your own machine (with extra options to suppress caching for one-off commands). After that we can make all sorts of command line helpers, integrations with dowhap the super system, etc. which will rely on being able to POST images or provide a URL, depending on the precise need in those cases

**Comment by jimdebeer** [comment]
Its not about making new cli commands its as a fallback for when things cant be installed, could use a post method indeed

**Comment by nikoloza** [comment]
@jimdebeer please check branch `feature/2-flexibilize`
